name: SnapTrash
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  camera: ^0.10.5+5
  firebase_auth: ^4.12.0
  firebase_core: ^2.20.0
  flutter:
    sdk: flutter
  geolocator: ^10.1.0
  google_fonts: ^4.0.4
  google_nav_bar: ^5.0.6
  # location: ^5.0.3
  lottie: ^2.3.2
  # permission_handler: ^11.0.1
  google_maps_flutter: ^2.5.3
  font_awesome_flutter: ^10.6.0
  google_gemini: ^0.1.2
  path: ^1.8.3
  path_provider: ^2.1.2
  dio: ^5.4.1
  cloud_firestore: ^4.15.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img.png
    - assets/
    - assets/animations/
    - assets/images/
    - assets/images/leaderboard/
    # - /data/user/0/com.example.snap_trash/cache/